<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="https://au1996.github.io/interview/css/index.css" />
  </head>
  <body>
    <p>
      <a href="https://promisesaplus.com/" target="_blank" rel="noopener noreferrer"
        >Promises/A+规范</a
      >
    </p>
    <p>
      <a
        href="https://malcolmyu.github.io/malnote/2015/06/12/Promises-A-Plus/"
        target="_blank"
        rel="noopener noreferrer"
        >Promises/A+规范（中文）</a
      >
    </p>
    <p>
      <a
        href="https://au1996.github.io/interview/promise/test/myPromise.js"
        target="_blank"
        rel="noopener noreferrer"
        >满足Promises/A+规范实现的Promise</a
      >
    </p>
    <pre>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          reject(111)
        }, 500)
      })
        .then(
          (res) => {
            console.log('Promise_result1', res)
          },
          (res) => {
            console.log('Promise_result2', res)
          }
        )
        .then((res) => {
          console.log('Promise_result3', res)
          throw Error('Promise_error')
        })
        .catch((err) => {
          console.log('Promise_catch', err)
        })
        .finally(() => {
          console.log('Promise_finally')
        })


      new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve('---------分割线---------')
        }, 500)
      }).then((res) => {
        console.log(res)
      })
      

      new MyPromise((resolve, reject) => {
        setTimeout(() => {
          reject(111)
        }, 500)
      })
        .then(
          (res) => {
            console.log('result1', res)
          },
          (res) => {
            console.log('result2', res)
          }
        )
        .then((res) => {
          console.log('result3', res)
          throw Error('my_error')
        })
        .catch((err) => {
          console.log('catch', err)
        })
        .finally(() => {
          console.log('finally')
        })
    </pre>
    <script src="./test/MyPromise-mini.js"></script>
    <script>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          reject(111)
        }, 500)
      })
        .then(
          (res) => {
            console.log('Promise_result1', res)
          },
          (res) => {
            console.log('Promise_result2', res)
          }
        )
        .then((res) => {
          console.log('Promise_result3', res)
          throw Error('Promise_error')
        })
        .catch((err) => {
          console.log('Promise_catch', err)
        })
        .finally(() => {
          console.log('Promise_finally')
        })
    </script>

    <script>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve('---------分割线---------')
        }, 500)
      }).then((res) => {
        console.log(res)
      })
    </script>

    <script>
      new MyPromise((resolve, reject) => {
        setTimeout(() => {
          reject(111)
        }, 500)
      })
        .then(
          (res) => {
            console.log('result1', res)
          },
          (res) => {
            console.log('result2', res)
          }
        )
        .then((res) => {
          console.log('result3', res)
          throw Error('my_error')
        })
        .catch((err) => {
          console.log('catch', err)
        })
        .finally(() => {
          console.log('finally')
        })
    </script>
  </body>
</html>
